# Generated by Django 4.1.13 on 2025-07-21 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_appuser_delete_user_alter_leavebalance_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('work_mode', models.CharField(choices=[('office', 'Office'), ('wfh', 'Work From Home')], max_length=10)),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='WorkFromHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
            ],
            options={
                'db_table': 'work_from_home',
            },
        ),
        migrations.RenameField(
            model_name='holiday',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='applied_at',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='hr_comment',
        ),
        migrations.AddField(
            model_name='appuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.department'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='employee_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('employee', 'Employee')], max_length=10),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual'), ('annual', 'Annual'), ('sick', 'Sick')], default='Default', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='holiday',
            table='holiday',
        ),
        migrations.AlterModelTable(
            name='leaverequest',
            table='leaverequest',
        ),
        migrations.DeleteModel(
            name='LeaveBalance',
        ),
        migrations.DeleteModel(
            name='LeaveType',
        ),
        migrations.AddField(
            model_name='workfromhome',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.appuser'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.appuser'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
